name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@latest

    - name: Set up Python
      uses: actions/setup-python@latest
      with:
        python-version: 3.8

    - name: Run tests
      run: pytest
